update ci

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -9,8 +9,8 @@ jobs:
       matrix:
         os: [ubuntu-latest]
         plan:
-          - ghc: '9.6.7'
-            resolver: 'lts-22.44'
+          - ghc: "9.12.2"
+            resolver: "lts-24.27"
         ## include:
         ##   - os: macOS-latest
         ##     flags: '--flag greskell:-hint-test'
@@ -22,48 +22,48 @@ jobs:
       FLAGS: ${{ matrix.flags }}
 
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - name: sqlite3 install
-      run: |
-        sudo apt install libsqlite3-dev
+      - name: sqlite3 install
+        run: |
+          sudo apt install libsqlite3-dev
 
-    - uses: haskell-actions/setup@v2
-      id: cabal-setup-haskell
-      with:
-        ghc-version: ${{ matrix.plan.ghc }}
-        enable-stack: true
+      - uses: haskell-actions/setup@v2
+        id: cabal-setup-haskell
+        with:
+          ghc-version: ${{ matrix.plan.ghc }}
+          enable-stack: true
 
-    - uses: actions/cache@v4
-      ## Looks like caching in macOS causes weird failures in the steps later.
-      if: runner.os != 'macOS'
-      with:
-        path: ~/.stack
-        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.plan.resolver }}
+      - uses: actions/cache@v4
+        ## Looks like caching in macOS causes weird failures in the steps later.
+        if: runner.os != 'macOS'
+        with:
+          path: ~/.stack
+          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.plan.resolver }}
 
-    - name: Configure
-      run: |
-        set -ex
-        rm -f stack.yaml.lock
-        $STACK clean
+      - name: Configure
+        run: |
+          set -ex
+          rm -f stack.yaml.lock
+          $STACK clean
 
-    - name: Install dependencies
-      run: $STACK test --bench --only-dependencies $FLAGS
-    - name: Build
-      run: $STACK build --bench --haddock --no-haddock-deps $FLAGS
-    - name: Install Binary
-      run: |
-        stack install --system-ghc --local-bin-path ./bin/
-    - name: Compress binaries
-      uses: crazy-max/ghaction-upx@v3
-      with:
-        version: latest
-        files: |
-          ./bin/*
-        args: -fq
-    - name: Upload Binary
-      uses: actions/upload-artifact@v4
-      with:
-        name: hs-hath-${{ matrix.os }}
-        path: |
-          ./bin/
+      - name: Install dependencies
+        run: $STACK test --bench --only-dependencies $FLAGS
+      - name: Build
+        run: $STACK build --bench --haddock --no-haddock-deps $FLAGS
+      - name: Install Binary
+        run: |
+          stack install --system-ghc --local-bin-path ./bin/
+      - name: Compress binaries
+        uses: crazy-max/ghaction-upx@v3
+        with:
+          version: latest
+          files: |
+            ./bin/*
+          args: -fq
+      - name: Upload Binary
+        uses: actions/upload-artifact@v4
+        with:
+          name: hs-hath-${{ matrix.os }}
+          path: |
+            ./bin/
